version: 0.0
os: linux
files:
  - source: .
    destination: /home/ununtu/build
    overwrite: yes

permissions:
  - object: /
    pattern : "**"
    mode : 755
    owner : ununtu
    group : ununtu

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ununtu

  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ununtu











